=== marcomontebello/distributed_programming/Assignment1/xsd/nffgInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="http://pad.polito.it/dp2/Assignment1/NetServices" xmlns:ns="http://pad.polito.it/dp2/Assignment1/NetServices">
    <xsd:element name="network_services">
    	
        <xsd:complexType>
    		<xsd:sequence>
    			<xsd:element name="nffg" type="ns:nffgType" minOccurs="0" maxOccurs="unbounded">
    			 
		   			 	<xsd:key name="id_node">
		    				<xsd:selector xpath="node"/>    		
		    				<xsd:field xpath="@name"/>  	    				    				    				  								
		  				</xsd:key>  
		  				<xsd:unique name="id_link">
		  					<xsd:selector xpath="node/link_ref"/>    		
		    				<xsd:field xpath="@name"/>
		  				</xsd:unique> 
					 			
					  	<xsd:keyref name="srcNode_ref" refer="ns:id_node">
				  			 <xsd:selector xpath="node/link_ref"/>
				  			<xsd:field xpath="@srcNode"/>  		
				  			 
				  		</xsd:keyref>
				  		  <xsd:keyref name="dstNode_ref" refer="ns:id_node">
				  			 <xsd:selector xpath="node/link_ref"/>
				  			<xsd:field xpath="@dstNode"/>  				 
				  		</xsd:keyref>					
  				</xsd:element>	
 		
  		    	<xsd:element name="policy" type="ns:Policy" minOccurs="0" maxOccurs="unbounded"/>	    		  
    		</xsd:sequence>  	
    	</xsd:complexType>
    		  	
    	<xsd:key name="id_nffg">
    		<xsd:selector xpath="nffg"/>
    		<xsd:field xpath="@name"/>
  		</xsd:key>	
  	
  		<xsd:keyref name="ref_nffg" refer="ns:id_nffg">
  			 <xsd:selector xpath="policy"/>
  			 <xsd:field xpath="@nffg_ref"/>		  			
  		</xsd:keyref>
  		
  		<xsd:key name="id_policy">
    		<xsd:selector xpath="policy"/>
    		<xsd:field xpath="@name"/>  		
  		</xsd:key>
  		 				
  		
</xsd:element>

   	<xsd:complexType name="nffgType">
   		<xsd:sequence>
   			<xsd:element name="node" type="ns:nodeType" minOccurs="1" maxOccurs="unbounded">
   				<xsd:unique name="idref_link">
	  				<xsd:selector xpath="link_ref"/>    				
	    			<xsd:field xpath="@name"/>
	  			</xsd:unique>
   			</xsd:element>
   		</xsd:sequence>
   		<xsd:attribute name="name" type="ns:SSN" use="required"/>
   		<xsd:attribute name="updateTime" type="xsd:dateTime"/>		
   		<xsd:attribute name="numberOfNodes" type="xsd:nonNegativeInteger"/>
   	</xsd:complexType>
	
	<xsd:complexType name="nodeType">
	   	<xsd:sequence>
	   	   <xsd:element name="link_ref" type="ns:linkType" minOccurs="0"  maxOccurs="unbounded"/>	   	   		
        </xsd:sequence>
  		<xsd:attribute name="name" type="ns:SSN" use="required"/>
  		<xsd:attribute name="function" type="ns:functionType" use="required" />
  		<xsd:attribute name="numberOfLinks" type="xsd:nonNegativeInteger" use="required" />	
   	</xsd:complexType>
 
   	      
  	<xsd:simpleType name="functionType">
	    <xsd:restriction base="xsd:string">
			<xsd:enumeration value="FW"/>
			<xsd:enumeration value="DPI"/>
			<xsd:enumeration value="NAT"/>
			<xsd:enumeration value="SPAM"/>
			<xsd:enumeration value="CACHE"/>
			<xsd:enumeration value="VPN"/>
			<xsd:enumeration value="WEB_SERVER"/>
			<xsd:enumeration value="WEB_CLIENT"/>
			<xsd:enumeration value="MAIL_SERVER"/>
			<xsd:enumeration value="MAIL_CLIENT"/>        
	    </xsd:restriction>
	</xsd:simpleType>

   	
    <xsd:complexType name="linkType">	
   		<xsd:sequence>		
   		</xsd:sequence>
   	   	<xsd:attribute name="name" type="ns:SSN" use="required"/>
   	   	<xsd:attribute name="srcNode" type="xsd:string" use="required"/>
   	   	<xsd:attribute name="dstNode" type="xsd:string" use="required"/>
   	
   	</xsd:complexType>
   	

   	<xsd:complexType name="Policy">
   		<xsd:sequence>
   		  	<xsd:element name="srcNode" type="ns:nodeRef" minOccurs="1" maxOccurs="1"/>
   			<xsd:element name="dstNode" type="ns:nodeRef" minOccurs="1" maxOccurs="1" />
    		<xsd:element name="verificationResult" type="ns:verificationresultType"/>
    		<xsd:sequence>	    		
	   			<xsd:element name="traversedFuncType" type="ns:functionType" minOccurs="0" maxOccurs="unbounded"/>
	   		</xsd:sequence> 
   		</xsd:sequence>
  		<xsd:attribute name="name" type="ns:SSN" use="required"/>
  		<xsd:attribute name="policyKind" type="ns:policyKindType" use="required"/>
  		<xsd:attribute name="nffg_ref" type="xsd:string" use="required"/>
  		<xsd:attribute name="policyLogic" type="ns:policyLogicType" use="required"/> 		
   	</xsd:complexType>

   	  <xsd:complexType name="nodeRef">
   	  		<xsd:sequence>
   	  		</xsd:sequence>
   			<xsd:attribute name="name" type="ns:SSN" use="required"/>  	  	
   	  </xsd:complexType>	
   	
   	<xsd:complexType name="verificationresultType">
   		<xsd:sequence>
   			<xsd:element name="resultMessage" type="xsd:string" />
   			<xsd:element name="result" type="ns:resultType"/>		
   		</xsd:sequence>
   		<xsd:attribute name="verificationTime" type="xsd:dateTime"/>
   	</xsd:complexType>

	<xsd:simpleType name="resultType">
	    <xsd:restriction base="xsd:string">
			<xsd:enumeration value="SATISFIED"/>
			<xsd:enumeration value="NOTSATISFIED"/>
		    <xsd:enumeration value="UNVERIFIED"/>		        
	    </xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="policyLogicType">
	    <xsd:restriction base="xsd:string">
			<xsd:enumeration value="POSITIVE"/>
			<xsd:enumeration value="NEGATIVE"/>
	    </xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="policyKindType">
	    <xsd:restriction base="xsd:string">
			<xsd:enumeration value="REACHABILITY"/>
			<xsd:enumeration value="TRAVERSAL"/>
	    </xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="SSN">
   		 <xsd:restriction base="xsd:token">
       		 <xsd:pattern value="[a-zA-Z][a-zA-Z0-9]*"/>
    	</xsd:restriction>
	</xsd:simpleType>
	
</xsd:schema>

=== marcomontebello/distributed_programming/Assignment1/xsd/nffgInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns:network_services xmlns:ns="http://pad.polito.it/dp2/Assignment1/NetServices" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pad.polito.it/dp2/Assignment1/NetServices nffgInfo.xsd ">

    <nffg name="Nffg1" updateTime="2016-09-25T19:42:20.000+02:00" numberOfNodes="22">
        <node name="MAILSERVER4" function="MAIL_SERVER" numberOfLinks="8">
            <link_ref name="Link12" srcNode="MAILSERVER4" dstNode="VPN12"/>
            <link_ref name="Link56" srcNode="MAILSERVER4" dstNode="NAT8"/>
            <link_ref name="Link130" srcNode="MAILSERVER4" dstNode="CACHE6"/>
            <link_ref name="Link10" srcNode="MAILSERVER4" dstNode="DPI9"/>
            <link_ref name="Link37" srcNode="MAILSERVER4" dstNode="FW4"/>
            <link_ref name="Link13" srcNode="MAILSERVER4" dstNode="VPN13"/>
            <link_ref name="Link24" srcNode="MAILSERVER4" dstNode="CACHE7"/>
            <link_ref name="Link82" srcNode="MAILSERVER4" dstNode="NAT0"/>
        </node>
        <node name="MAILSERVER3" function="MAIL_SERVER" numberOfLinks="5">
            <link_ref name="Link33" srcNode="MAILSERVER3" dstNode="VPN1"/>
            <link_ref name="Link111" srcNode="MAILSERVER3" dstNode="VPN13"/>
            <link_ref name="Link118" srcNode="MAILSERVER3" dstNode="NAT8"/>
            <link_ref name="Link8" srcNode="MAILSERVER3" dstNode="DPI9"/>
            <link_ref name="Link104" srcNode="MAILSERVER3" dstNode="SPAM5"/>
        </node>
        <node name="FW4" function="FW" numberOfLinks="7">
            <link_ref name="Link22" srcNode="FW4" dstNode="NAT8"/>
            <link_ref name="Link65" srcNode="FW4" dstNode="VPN14"/>
            <link_ref name="Link42" srcNode="FW4" dstNode="SPAM5"/>
            <link_ref name="Link53" srcNode="FW4" dstNode="MAILSERVER4"/>
            <link_ref name="Link110" srcNode="FW4" dstNode="NAT3"/>
            <link_ref name="Link52" srcNode="FW4" dstNode="CACHE7"/>
            <link_ref name="Link50" srcNode="FW4" dstNode="VPN12"/>
        </node>
        <node name="NAT10" function="NAT" numberOfLinks="5">
            <link_ref name="Link89" srcNode="NAT10" dstNode="WEBCLIENT0"/>
            <link_ref name="Link76" srcNode="NAT10" dstNode="VPN12"/>
            <link_ref name="Link14" srcNode="NAT10" dstNode="VPN1"/>
            <link_ref name="Link58" srcNode="NAT10" dstNode="DPI9"/>
            <link_ref name="Link73" srcNode="NAT10" dstNode="SPAM2"/>
        </node>
        <node name="NAT0" function="NAT" numberOfLinks="4">
            <link_ref name="Link131" srcNode="NAT0" dstNode="NAT10"/>
            <link_ref name="Link43" srcNode="NAT0" dstNode="CACHE7"/>
            <link_ref name="Link1" srcNode="NAT0" dstNode="WEBCLIENT0"/>
            <link_ref name="Link124" srcNode="NAT0" dstNode="VPN1"/>
        </node>
        <node name="MAILSERVER1" function="MAIL_SERVER" numberOfLinks="4">
            <link_ref name="Link81" srcNode="MAILSERVER1" dstNode="VPN14"/>
            <link_ref name="Link106" srcNode="MAILSERVER1" dstNode="CACHE7"/>
            <link_ref name="Link4" srcNode="MAILSERVER1" dstNode="CACHE15"/>
            <link_ref name="Link41" srcNode="MAILSERVER1" dstNode="VPN1"/>
        </node>
        <node name="MAILSERVER0" function="MAIL_SERVER" numberOfLinks="3">
            <link_ref name="Link31" srcNode="MAILSERVER0" dstNode="CACHE7"/>
            <link_ref name="Link2" srcNode="MAILSERVER0" dstNode="CACHE15"/>
            <link_ref name="Link126" srcNode="MAILSERVER0" dstNode="VPN1"/>
        </node>
        <node name="FW11" function="FW" numberOfLinks="3">
            <link_ref name="Link46" srcNode="FW11" dstNode="CACHE7"/>
            <link_ref name="Link74" srcNode="FW11" dstNode="VPN14"/>
            <link_ref name="Link71" srcNode="FW11" dstNode="WEBCLIENT0"/>
        </node>
        <node name="NAT8" function="NAT" numberOfLinks="7">
            <link_ref name="Link98" srcNode="NAT8" dstNode="DPI9"/>
            <link_ref name="Link16" srcNode="NAT8" dstNode="NAT0"/>
            <link_ref name="Link26" srcNode="NAT8" dstNode="NAT10"/>
            <link_ref name="Link68" srcNode="NAT8" dstNode="FW4"/>
            <link_ref name="Link79" srcNode="NAT8" dstNode="VPN1"/>
            <link_ref name="Link105" srcNode="NAT8" dstNode="CACHE7"/>
            <link_ref name="Link18" srcNode="NAT8" dstNode="WEBCLIENT0"/>
        </node>
        <node name="VPN12" function="VPN" numberOfLinks="8">
            <link_ref name="Link64" srcNode="VPN12" dstNode="VPN1"/>
            <link_ref name="Link15" srcNode="VPN12" dstNode="WEBSERVER2"/>
            <link_ref name="Link59" srcNode="VPN12" dstNode="NAT10"/>
            <link_ref name="Link91" srcNode="VPN12" dstNode="NAT8"/>
            <link_ref name="Link119" srcNode="VPN12" dstNode="CACHE6"/>
            <link_ref name="Link17" srcNode="VPN12" dstNode="FW4"/>
            <link_ref name="Link129" srcNode="VPN12" dstNode="WEBCLIENT0"/>
            <link_ref name="Link84" srcNode="VPN12" dstNode="NAT3"/>
        </node>
        <node name="VPN1" function="VPN" numberOfLinks="8">
            <link_ref name="Link77" srcNode="VPN1" dstNode="VPN13"/>
            <link_ref name="Link75" srcNode="VPN1" dstNode="NAT8"/>
            <link_ref name="Link80" srcNode="VPN1" dstNode="FW11"/>
            <link_ref name="Link39" srcNode="VPN1" dstNode="SPAM2"/>
            <link_ref name="Link30" srcNode="VPN1" dstNode="DPI9"/>
            <link_ref name="Link102" srcNode="VPN1" dstNode="MAILSERVER1"/>
            <link_ref name="Link95" srcNode="VPN1" dstNode="CACHE7"/>
            <link_ref name="Link94" srcNode="VPN1" dstNode="MAILSERVER0"/>
        </node>
        <node name="NAT3" function="NAT" numberOfLinks="9">
            <link_ref name="Link97" srcNode="NAT3" dstNode="CACHE6"/>
            <link_ref name="Link38" srcNode="NAT3" dstNode="SPAM2"/>
            <link_ref name="Link19" srcNode="NAT3" dstNode="WEBCLIENT0"/>
            <link_ref name="Link107" srcNode="NAT3" dstNode="NAT0"/>
            <link_ref name="Link85" srcNode="NAT3" dstNode="FW4"/>
            <link_ref name="Link112" srcNode="NAT3" dstNode="CACHE15"/>
            <link_ref name="Link61" srcNode="NAT3" dstNode="WEBSERVER2"/>
            <link_ref name="Link114" srcNode="NAT3" dstNode="VPN12"/>
            <link_ref name="Link125" srcNode="NAT3" dstNode="CACHE7"/>
        </node>
        <node name="VPN14" function="VPN" numberOfLinks="5">
            <link_ref name="Link66" srcNode="VPN14" dstNode="NAT0"/>
            <link_ref name="Link54" srcNode="VPN14" dstNode="CACHE15"/>
            <link_ref name="Link121" srcNode="VPN14" dstNode="MAILSERVER3"/>
            <link_ref name="Link113" srcNode="VPN14" dstNode="FW11"/>
            <link_ref name="Link51" srcNode="VPN14" dstNode="CACHE7"/>
        </node>
        <node name="VPN13" function="VPN" numberOfLinks="8">
            <link_ref name="Link78" srcNode="VPN13" dstNode="CACHE7"/>
            <link_ref name="Link20" srcNode="VPN13" dstNode="WEBSERVER2"/>
            <link_ref name="Link35" srcNode="VPN13" dstNode="NAT10"/>
            <link_ref name="Link116" srcNode="VPN13" dstNode="VPN14"/>
            <link_ref name="Link127" srcNode="VPN13" dstNode="NAT3"/>
            <link_ref name="Link101" srcNode="VPN13" dstNode="MAILSERVER0"/>
            <link_ref name="Link115" srcNode="VPN13" dstNode="VPN12"/>
            <link_ref name="Link93" srcNode="VPN13" dstNode="FW4"/>
        </node>
        <node name="CACHE15" function="CACHE" numberOfLinks="8">
            <link_ref name="Link120" srcNode="CACHE15" dstNode="NAT0"/>
            <link_ref name="Link88" srcNode="CACHE15" dstNode="VPN1"/>
            <link_ref name="Link99" srcNode="CACHE15" dstNode="NAT8"/>
            <link_ref name="Link49" srcNode="CACHE15" dstNode="VPN13"/>
            <link_ref name="Link128" srcNode="CACHE15" dstNode="WEBCLIENT0"/>
            <link_ref name="Link3" srcNode="CACHE15" dstNode="MAILSERVER0"/>
            <link_ref name="Link5" srcNode="CACHE15" dstNode="MAILSERVER1"/>
            <link_ref name="Link72" srcNode="CACHE15" dstNode="DPI9"/>
        </node>
        <node name="SPAM5" function="SPAM" numberOfLinks="4">
            <link_ref name="Link67" srcNode="SPAM5" dstNode="NAT0"/>
            <link_ref name="Link21" srcNode="SPAM5" dstNode="MAILSERVER4"/>
            <link_ref name="Link25" srcNode="SPAM5" dstNode="CACHE6"/>
            <link_ref name="Link47" srcNode="SPAM5" dstNode="FW4"/>
        </node>
        <node name="CACHE6" function="CACHE" numberOfLinks="6">
            <link_ref name="Link44" srcNode="CACHE6" dstNode="NAT3"/>
            <link_ref name="Link100" srcNode="CACHE6" dstNode="MAILSERVER0"/>
            <link_ref name="Link122" srcNode="CACHE6" dstNode="VPN13"/>
            <link_ref name="Link70" srcNode="CACHE6" dstNode="NAT10"/>
            <link_ref name="Link90" srcNode="CACHE6" dstNode="DPI9"/>
            <link_ref name="Link63" srcNode="CACHE6" dstNode="VPN14"/>
        </node>
        <node name="DPI9" function="DPI" numberOfLinks="7">
            <link_ref name="Link34" srcNode="DPI9" dstNode="MAILSERVER0"/>
            <link_ref name="Link11" srcNode="DPI9" dstNode="MAILSERVER4"/>
            <link_ref name="Link87" srcNode="DPI9" dstNode="MAILSERVER1"/>
            <link_ref name="Link48" srcNode="DPI9" dstNode="SPAM5"/>
            <link_ref name="Link7" srcNode="DPI9" dstNode="WEBSERVER2"/>
            <link_ref name="Link9" srcNode="DPI9" dstNode="MAILSERVER3"/>
            <link_ref name="Link60" srcNode="DPI9" dstNode="CACHE6"/>
        </node>
        <node name="WEBCLIENT0" function="WEB_CLIENT" numberOfLinks="5">
            <link_ref name="Link27" srcNode="WEBCLIENT0" dstNode="FW11"/>
            <link_ref name="Link0" srcNode="WEBCLIENT0" dstNode="NAT0"/>
            <link_ref name="Link29" srcNode="WEBCLIENT0" dstNode="VPN14"/>
